# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APNs-labs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APNs-labs
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'

  target 'APNs-labsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APNs-labsUITests' do
    # Pods for testing
  end

end
