# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'calendar-labs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for calendar-labs
  pod 'SnapKit', '~> 5.0.0'
  pod 'FSCalendar'
  target 'calendar-labsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'calendar-labsUITests' do
    # Pods for testing
  end

end
